### ISSUE TITLE
Add Native Linux Support

### ISSUE THREAD

**Issue by matej118111** [abrahampo1/roam-desktop#1]
Yeah so i tried running it using wine, it didn't work do you know how to fix it?

![image](https://user-images.githubusercontent.com/51799660/176752302-b45eb5c5-a39d-461c-b6d9-3cd0b60aaf20.png)
It showed the logo but after minimalizing the application or resizing it dissapeared

**Comment by abrahampo1** [comment]
> Yeah so i tried running it using wine, it didn't work do you know how to fix it?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/51799660/176752302-b45eb5c5-a39d-461c-b6d9-3cd0b60aaf20.png)
> 
> It showed the logo but after minimalizing the application or resizing it dissapeared
> 
> 

You dont need to use WINE, i will compile it for native linux on this week, so dont worry about that

**Comment by matej118111** [comment]
Oh ok sure, thanks

**Comment by abrahampo1** [comment]
> Oh ok sure, thanks

https://github.com/abrahampo1/roam-desktop/releases/tag/1.0.0

Here you have, the snap and AppImage
