### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by SwoopedGalaxySG** [abrahampo1/roam-desktop#2]

**Comment by SwoopedGalaxySG** [comment]
Just asking, when it will be available for MacOS users?

**Comment by abrahampo1** [comment]
As soon as i get a mac to compile it

**Comment by abrahampo1** [comment]
> Just asking, when it will be available for MacOS users?

I dont have access to any mac, can you help me to compile? add me on dc: abrahampo1#0069

**Comment by SwoopedGalaxySG** [comment]
Friend rq sent! Glad that I can help you compile! My user is air#5400

**Comment by abrahampo1** [comment]
Added on the releases page
